# Generated by Django 3.1.3 on 2020-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201122_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
