# Generated by Django 3.1.3 on 2020-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_cost', models.PositiveIntegerField()),
                ('service_description', models.TextField()),
            ],
        ),
    ]
