# Generated by Django 3.1.3 on 2020-11-15 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='admission',
        ),
        migrations.AddField(
            model_name='case',
            name='admission_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='medication_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.medication'),
        ),
        migrations.AlterField(
            model_name='case',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.service'),
        ),
    ]
