# Generated by Django 3.1.3 on 2020-11-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_auto_20201115_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='admission_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
