# Generated by Django 3.1.3 on 2020-11-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0007_bill_admission_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.case'),
        ),
    ]
